

[mongodb]
mongodb.sriharidevops17.online

[redis]
redis.sriharidevops17.online

[mysql]
mysql.sriharidevops17.online

[rabbitmq]
rabbitmq.sriharidevops17.online

[catalogue]
catalogue.sriharidevops17.online

[user]
user.sriharidevops17.online

[cart]
cart.sriharidevops17.online

[shipping]
shipping.sriharidevops17.online

[payment]
payment.sriharidevops17.online

[frontend]
frontend.sriharidevops17.online


[local]
localhost

[all:vars]
ansible_user=ec2-user
ansible_password=DevOps321

[local:vars]
course=ansible
duration=10hrs
trainer=sivakumar
#name=from inventory

